services:
  backend:
    build: .
    env_file:
      - .env
    ports:
      - "3333:3000"
    # environment:
    # PORT: 3333
    # DATABASE_URL: "postgresql://neondb_owner:npg_FqPbj43OnLIw@ep-patient-union-aclkqsj7-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    # GITHUB_CLIENT_ID: "Ov23liAXviVZG2XVBB79"
    # GITHUB_CLIENT_SECRET: "d1ef344d73a340128972523d5967cdc45f440fb6"
    # JWT_SECRET: "njdbsjabD455464aDsa16ADs62asdc25"
